# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WriteDataset <- function(dataset, mat, datatype) {
    .Call('h5_WriteDataset', PACKAGE = 'h5', dataset, mat, datatype)
}

GetDataSetType <- function(dataset) {
    .Call('h5_GetDataSetType', PACKAGE = 'h5', dataset)
}

ReadDataset <- function(dataset, offset, count) {
    .Call('h5_ReadDataset', PACKAGE = 'h5', dataset, offset, count)
}

CloseDataset <- function(dataset) {
    .Call('h5_CloseDataset', PACKAGE = 'h5', dataset)
}

CreateDataset <- function(file, datasetname, datatype, dimensions, chunksize, maxshape, compressionlevel, size) {
    .Call('h5_CreateDataset', PACKAGE = 'h5', file, datasetname, datatype, dimensions, chunksize, maxshape, compressionlevel, size)
}

OpenDataset <- function(file, datasetname) {
    .Call('h5_OpenDataset', PACKAGE = 'h5', file, datasetname)
}

OpenFile <- function(filePath, mode) {
    .Call('h5_OpenFile', PACKAGE = 'h5', filePath, mode)
}

CloseFile <- function(file) {
    .Call('h5_CloseFile', PACKAGE = 'h5', file)
}

CreateGroup <- function(file, groupname) {
    .Call('h5_CreateGroup', PACKAGE = 'h5', file, groupname)
}

OpenGroup <- function(file, groupname) {
    .Call('h5_OpenGroup', PACKAGE = 'h5', file, groupname)
}

CloseGroup <- function(group) {
    .Call('h5_CloseGroup', PACKAGE = 'h5', group)
}

ExistsGroup <- function(file, groupname) {
    .Call('h5_ExistsGroup', PACKAGE = 'h5', file, groupname)
}

