# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WriteDataset <- function(dataset, dataspace, mat, datatype, count) {
    .Call('h5_WriteDataset', PACKAGE = 'h5', dataset, dataspace, mat, datatype, count)
}

ExtendDataset <- function(dset, dimsnew) {
    .Call('h5_ExtendDataset', PACKAGE = 'h5', dset, dimsnew)
}

GetDataSetType <- function(dataset) {
    .Call('h5_GetDataSetType', PACKAGE = 'h5', dataset)
}

ReadDataset <- function(dataset, dataspace, count) {
    .Call('h5_ReadDataset', PACKAGE = 'h5', dataset, dataspace, count)
}

CloseDataset <- function(dataset) {
    .Call('h5_CloseDataset', PACKAGE = 'h5', dataset)
}

CreateDataset <- function(file, datasetname, datatype, dimensions, chunksize, maxshape, compressionlevel, size) {
    .Call('h5_CreateDataset', PACKAGE = 'h5', file, datasetname, datatype, dimensions, chunksize, maxshape, compressionlevel, size)
}

OpenDataset <- function(file, datasetname) {
    .Call('h5_OpenDataset', PACKAGE = 'h5', file, datasetname)
}

GetDataSetDimensions <- function(dataset) {
    .Call('h5_GetDataSetDimensions', PACKAGE = 'h5', dataset)
}

GetDataSetMaxDimensions <- function(dataset) {
    .Call('h5_GetDataSetMaxDimensions', PACKAGE = 'h5', dataset)
}

GetDataSetChunksize <- function(dataset) {
    .Call('h5_GetDataSetChunksize', PACKAGE = 'h5', dataset)
}

GetDataSetCompression <- function(dataset) {
    .Call('h5_GetDataSetCompression', PACKAGE = 'h5', dataset)
}

GetDataspace <- function(dataset, offset, count) {
    .Call('h5_GetDataspace', PACKAGE = 'h5', dataset, offset, count)
}

GetDataspaceElem <- function(dataset, coords) {
    .Call('h5_GetDataspaceElem', PACKAGE = 'h5', dataset, coords)
}

GetDataspaceAll <- function(dataset) {
    .Call('h5_GetDataspaceAll', PACKAGE = 'h5', dataset)
}

CloseDataspace <- function(dataspace) {
    .Call('h5_CloseDataspace', PACKAGE = 'h5', dataspace)
}

OpenFile <- function(filePath, mode) {
    .Call('h5_OpenFile', PACKAGE = 'h5', filePath, mode)
}

CloseFile <- function(file) {
    .Call('h5_CloseFile', PACKAGE = 'h5', file)
}

FlushFile <- function(file) {
    .Call('h5_FlushFile', PACKAGE = 'h5', file)
}

CreateGroup <- function(file, groupname) {
    .Call('h5_CreateGroup', PACKAGE = 'h5', file, groupname)
}

OpenGroup <- function(file, groupname) {
    .Call('h5_OpenGroup', PACKAGE = 'h5', file, groupname)
}

CloseGroup <- function(group) {
    .Call('h5_CloseGroup', PACKAGE = 'h5', group)
}

ExistsGroup <- function(file, groupname) {
    .Call('h5_ExistsGroup', PACKAGE = 'h5', file, groupname)
}

